# See [Source Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-redshift:dev
tests:
  spec:
    - spec_path: "src/main/resources/spec.json"
